name: E2E Tests

on:
  pull_request:
    branches: ["main"]
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/e2e-tests.yml"
      - "yarn.lock"
      - "tsconfig.json"
      - "nest-cli.json"

  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "test/**"
      - ".github/workflows/e2e-tests.yml"
      - "yarn.lock"
      - "tsconfig.json"
      - "nest-cli.json"

  workflow_dispatch:

jobs:
  e2e:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      BASE_URL: ${{ secrets.BASE_URL }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
      JWT_TOKEN_EXPIRATION: ${{ secrets.JWT_TOKEN_EXPIRATION }}
      TEST_ADMIN_USERNAME: ${{ secrets.TEST_ADMIN_USERNAME }}
      TEST_ADMIN_PASSWORD: ${{ secrets.TEST_ADMIN_PASSWORD }}

      MONGO_HOST: ${{ secrets.MONGO_HOST }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_REPLICA_SET: ${{ secrets.MONGO_REPLICA_SET }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Start MongoDB with replica set
        run: |
          docker run -d \
            --name mongo-rs \
            -p ${{ env.MONGO_PORT }}:${{ env.MONGO_PORT }} \
            mongo:6.0 --replSet ${{ env.MONGO_REPLICA_SET }}

          echo "Waiting for MongoDB to start..."
          sleep 5

          docker exec mongo-rs mongosh --eval "rs.initiate({_id: '${{ env.MONGO_REPLICA_SET }}', members: [{ _id: 0, host: '${{ env.MONGO_HOST }}:${{ env.MONGO_PORT }}' }]})"

          sleep 5

      - name: Seed test admin user into collection
        run: |
          node -e '
            const { MongoClient } = require("mongodb");
            const bcrypt = require("bcrypt");
            (async () => {
              const client = new MongoClient(`mongodb://${process.env.MONGO_HOST}:${process.env.MONGO_PORT}`);
              await client.connect();
              const db = client.db(process.env.MONGO_DB_NAME);
              const employees = db.collection("employees");

              const exists = await employees.findOne({ username: process.env.TEST_ADMIN_USERNAME });
              if (!exists) {
                const hashedPassword = await bcrypt.hash(process.env.TEST_ADMIN_PASSWORD, 8);
                await employees.insertOne({
                  username: process.env.TEST_ADMIN_USERNAME,
                  password: hashedPassword,
                  role: "admin",
                  fullName: "Admin Test",
                  cpf: "00000000000",
                  createdAt: new Date(),
                  updatedAt: new Date(),
                });
                console.log("Admin user created");
              } else {
                console.log("Admin user already exists, skipping seed.");
              }

              await client.close();
            })();
          '

      - name: Run E2E tests
        run: yarn test:e2e

      - name: Cleanup MongoDB container
        if: always()
        run: |
          docker stop mongo-rs || true
          docker rm mongo-rs || true
